package io.github.amarcinkowski

import groovy.util.logging.Slf4j
import io.github.amarcinkowski.chess.board.Direction
import io.github.amarcinkowski.chess.board.utils.CoordinateUtil

import static io.github.amarcinkowski.chess.board.Direction.*;


/**
 * Used to generate enum below
 */
class Generator {

        private static String[] possibleMoves(Direction direction, int x, int y) {
                def ret = []
                for (int stepSize in 1..7) {
                        if ([NNE, NNW, SSE, SSW, NEE, NWW, SEE, SWW].contains(direction)) {
                                if (stepSize != 2) {
                                        continue // leave only proper Knight moves
                                }
                        }
                        def newx = x + direction.xstep * stepSize
                        def newy = y + (int) (direction.ystep * stepSize)
                        if (newx > 8 || newx < 1) break
                        if (newy > 8 || newy < 1) break
                        ret += "'${CoordinateUtil.x2a(newx)}$newy'"
                }
                ret
        }

        private static allDirections(int x, int y) {
                def s = ""
                for (Direction d : Direction.values()) {
                        s += "\n\t\t$d:${possibleMoves(d, x, y)},"
                }
                s
        }

        public static void main(String[] args) {
                for (int y in 1..8) {
                        for (int x in 1..8) {
                                println """${CoordinateUtil.x2a(x)}${y} (${CoordinateUtil.xy2n(x, y)}, [$x,$y],
\t\t[ /* squares in directions from ${CoordinateUtil.x2a(x)}${y}*/${allDirections(x, y)}\n\t] as Map),
"""
                        }
                }
        }
}

@Slf4j
public enum Square {

        A1(1, [1, 1],
                [ /* squares in directions from A1*/
                  NNW: [],
                  NNE: ['B3'],
                  NW : [],
                  N  : ['A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
                  NE : ['B2', 'C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
                  NWW: [],
                  NEE: ['C2'],
                  W  : [],
                  E  : ['B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        B1(2, [2, 1],
                [ /* squares in directions from B1*/
                  NNW: ['A3'],
                  NNE: ['C3'],
                  NW : ['A2'],
                  N  : ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
                  NE : ['C2', 'D3', 'E4', 'F5', 'G6', 'H7'],
                  NWW: [],
                  NEE: ['D2'],
                  W  : ['A1'],
                  E  : ['C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        C1(3, [3, 1],
                [ /* squares in directions from C1*/
                  NNW: ['B3'],
                  NNE: ['D3'],
                  NW : ['B2', 'A3'],
                  N  : ['C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
                  NE : ['D2', 'E3', 'F4', 'G5', 'H6'],
                  NWW: ['A2'],
                  NEE: ['E2'],
                  W  : ['B1', 'A1'],
                  E  : ['D1', 'E1', 'F1', 'G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        D1(4, [4, 1],
                [ /* squares in directions from D1*/
                  NNW: ['C3'],
                  NNE: ['E3'],
                  NW : ['C2', 'B3', 'A4'],
                  N  : ['D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
                  NE : ['E2', 'F3', 'G4', 'H5'],
                  NWW: ['B2'],
                  NEE: ['F2'],
                  W  : ['C1', 'B1', 'A1'],
                  E  : ['E1', 'F1', 'G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        E1(5, [5, 1],
                [ /* squares in directions from E1*/
                  NNW: ['D3'],
                  NNE: ['F3'],
                  NW : ['D2', 'C3', 'B4', 'A5'],
                  N  : ['E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
                  NE : ['F2', 'G3', 'H4'],
                  NWW: ['C2'],
                  NEE: ['G2'],
                  W  : ['D1', 'C1', 'B1', 'A1'],
                  E  : ['F1', 'G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        F1(6, [6, 1],
                [ /* squares in directions from F1*/
                  NNW: ['E3'],
                  NNE: ['G3'],
                  NW : ['E2', 'D3', 'C4', 'B5', 'A6'],
                  N  : ['F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
                  NE : ['G2', 'H3'],
                  NWW: ['D2'],
                  NEE: ['H2'],
                  W  : ['E1', 'D1', 'C1', 'B1', 'A1'],
                  E  : ['G1', 'H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        G1(7, [7, 1],
                [ /* squares in directions from G1*/
                  NNW: ['F3'],
                  NNE: ['H3'],
                  NW : ['F2', 'E3', 'D4', 'C5', 'B6', 'A7'],
                  N  : ['G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
                  NE : ['H2'],
                  NWW: ['E2'],
                  NEE: [],
                  W  : ['F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
                  E  : ['H1'],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        H1(8, [8, 1],
                [ /* squares in directions from H1*/
                  NNW: ['G3'],
                  NNE: [],
                  NW : ['G2', 'F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
                  N  : ['H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
                  NE : [],
                  NWW: ['F2'],
                  NEE: [],
                  W  : ['G1', 'F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
                  E  : [],
                  SWW: [],
                  SEE: [],
                  SW : [],
                  S  : [],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        A2(9, [1, 2],
                [ /* squares in directions from A2*/
                  NNW: [],
                  NNE: ['B4'],
                  NW : [],
                  N  : ['A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
                  NE : ['B3', 'C4', 'D5', 'E6', 'F7', 'G8'],
                  NWW: [],
                  NEE: ['C3'],
                  W  : [],
                  E  : ['B2', 'C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
                  SWW: [],
                  SEE: ['C1'],
                  SW : [],
                  S  : ['A1'],
                  SE : ['B1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        B2(10, [2, 2],
                [ /* squares in directions from B2*/
                  NNW: ['A4'],
                  NNE: ['C4'],
                  NW : ['A3'],
                  N  : ['B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
                  NE : ['C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
                  NWW: [],
                  NEE: ['D3'],
                  W  : ['A2'],
                  E  : ['C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
                  SWW: [],
                  SEE: ['D1'],
                  SW : ['A1'],
                  S  : ['B1'],
                  SE : ['C1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        C2(11, [3, 2],
                [ /* squares in directions from C2*/
                  NNW: ['B4'],
                  NNE: ['D4'],
                  NW : ['B3', 'A4'],
                  N  : ['C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
                  NE : ['D3', 'E4', 'F5', 'G6', 'H7'],
                  NWW: ['A3'],
                  NEE: ['E3'],
                  W  : ['B2', 'A2'],
                  E  : ['D2', 'E2', 'F2', 'G2', 'H2'],
                  SWW: ['A1'],
                  SEE: ['E1'],
                  SW : ['B1'],
                  S  : ['C1'],
                  SE : ['D1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        D2(12, [4, 2],
                [ /* squares in directions from D2*/
                  NNW: ['C4'],
                  NNE: ['E4'],
                  NW : ['C3', 'B4', 'A5'],
                  N  : ['D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
                  NE : ['E3', 'F4', 'G5', 'H6'],
                  NWW: ['B3'],
                  NEE: ['F3'],
                  W  : ['C2', 'B2', 'A2'],
                  E  : ['E2', 'F2', 'G2', 'H2'],
                  SWW: ['B1'],
                  SEE: ['F1'],
                  SW : ['C1'],
                  S  : ['D1'],
                  SE : ['E1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        E2(13, [5, 2],
                [ /* squares in directions from E2*/
                  NNW: ['D4'],
                  NNE: ['F4'],
                  NW : ['D3', 'C4', 'B5', 'A6'],
                  N  : ['E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
                  NE : ['F3', 'G4', 'H5'],
                  NWW: ['C3'],
                  NEE: ['G3'],
                  W  : ['D2', 'C2', 'B2', 'A2'],
                  E  : ['F2', 'G2', 'H2'],
                  SWW: ['C1'],
                  SEE: ['G1'],
                  SW : ['D1'],
                  S  : ['E1'],
                  SE : ['F1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        F2(14, [6, 2],
                [ /* squares in directions from F2*/
                  NNW: ['E4'],
                  NNE: ['G4'],
                  NW : ['E3', 'D4', 'C5', 'B6', 'A7'],
                  N  : ['F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
                  NE : ['G3', 'H4'],
                  NWW: ['D3'],
                  NEE: ['H3'],
                  W  : ['E2', 'D2', 'C2', 'B2', 'A2'],
                  E  : ['G2', 'H2'],
                  SWW: ['D1'],
                  SEE: ['H1'],
                  SW : ['E1'],
                  S  : ['F1'],
                  SE : ['G1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        G2(15, [7, 2],
                [ /* squares in directions from G2*/
                  NNW: ['F4'],
                  NNE: ['H4'],
                  NW : ['F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
                  N  : ['G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
                  NE : ['H3'],
                  NWW: ['E3'],
                  NEE: [],
                  W  : ['F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
                  E  : ['H2'],
                  SWW: ['E1'],
                  SEE: [],
                  SW : ['F1'],
                  S  : ['G1'],
                  SE : ['H1'],
                  SSW: [],
                  SSE: [],
                ] as Map),

        H2(16, [8, 2],
                [ /* squares in directions from H2*/
                  NNW: ['G4'],
                  NNE: [],
                  NW : ['G3', 'F4', 'E5', 'D6', 'C7', 'B8'],
                  N  : ['H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
                  NE : [],
                  NWW: ['F3'],
                  NEE: [],
                  W  : ['G2', 'F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
                  E  : [],
                  SWW: ['F1'],
                  SEE: [],
                  SW : ['G1'],
                  S  : ['H1'],
                  SE : [],
                  SSW: [],
                  SSE: [],
                ] as Map),

        A3(17, [1, 3],
                [ /* squares in directions from A3*/
                  NNW: [],
                  NNE: ['B5'],
                  NW : [],
                  N  : ['A4', 'A5', 'A6', 'A7', 'A8'],
                  NE : ['B4', 'C5', 'D6', 'E7', 'F8'],
                  NWW: [],
                  NEE: ['C4'],
                  W  : [],
                  E  : ['B3', 'C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
                  SWW: [],
                  SEE: ['C2'],
                  SW : [],
                  S  : ['A2', 'A1'],
                  SE : ['B2', 'C1'],
                  SSW: [],
                  SSE: ['B1'],
                ] as Map),

        B3(18, [2, 3],
                [ /* squares in directions from B3*/
                  NNW: ['A5'],
                  NNE: ['C5'],
                  NW : ['A4'],
                  N  : ['B4', 'B5', 'B6', 'B7', 'B8'],
                  NE : ['C4', 'D5', 'E6', 'F7', 'G8'],
                  NWW: [],
                  NEE: ['D4'],
                  W  : ['A3'],
                  E  : ['C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
                  SWW: [],
                  SEE: ['D2'],
                  SW : ['A2'],
                  S  : ['B2', 'B1'],
                  SE : ['C2', 'D1'],
                  SSW: ['A1'],
                  SSE: ['C1'],
                ] as Map),

        C3(19, [3, 3],
                [ /* squares in directions from C3*/
                  NNW: ['B5'],
                  NNE: ['D5'],
                  NW : ['B4', 'A5'],
                  N  : ['C4', 'C5', 'C6', 'C7', 'C8'],
                  NE : ['D4', 'E5', 'F6', 'G7', 'H8'],
                  NWW: ['A4'],
                  NEE: ['E4'],
                  W  : ['B3', 'A3'],
                  E  : ['D3', 'E3', 'F3', 'G3', 'H3'],
                  SWW: ['A2'],
                  SEE: ['E2'],
                  SW : ['B2', 'A1'],
                  S  : ['C2', 'C1'],
                  SE : ['D2', 'E1'],
                  SSW: ['B1'],
                  SSE: ['D1'],
                ] as Map),

        D3(20, [4, 3],
                [ /* squares in directions from D3*/
                  NNW: ['C5'],
                  NNE: ['E5'],
                  NW : ['C4', 'B5', 'A6'],
                  N  : ['D4', 'D5', 'D6', 'D7', 'D8'],
                  NE : ['E4', 'F5', 'G6', 'H7'],
                  NWW: ['B4'],
                  NEE: ['F4'],
                  W  : ['C3', 'B3', 'A3'],
                  E  : ['E3', 'F3', 'G3', 'H3'],
                  SWW: ['B2'],
                  SEE: ['F2'],
                  SW : ['C2', 'B1'],
                  S  : ['D2', 'D1'],
                  SE : ['E2', 'F1'],
                  SSW: ['C1'],
                  SSE: ['E1'],
                ] as Map),

        E3(21, [5, 3],
                [ /* squares in directions from E3*/
                  NNW: ['D5'],
                  NNE: ['F5'],
                  NW : ['D4', 'C5', 'B6', 'A7'],
                  N  : ['E4', 'E5', 'E6', 'E7', 'E8'],
                  NE : ['F4', 'G5', 'H6'],
                  NWW: ['C4'],
                  NEE: ['G4'],
                  W  : ['D3', 'C3', 'B3', 'A3'],
                  E  : ['F3', 'G3', 'H3'],
                  SWW: ['C2'],
                  SEE: ['G2'],
                  SW : ['D2', 'C1'],
                  S  : ['E2', 'E1'],
                  SE : ['F2', 'G1'],
                  SSW: ['D1'],
                  SSE: ['F1'],
                ] as Map),

        F3(22, [6, 3],
                [ /* squares in directions from F3*/
                  NNW: ['E5'],
                  NNE: ['G5'],
                  NW : ['E4', 'D5', 'C6', 'B7', 'A8'],
                  N  : ['F4', 'F5', 'F6', 'F7', 'F8'],
                  NE : ['G4', 'H5'],
                  NWW: ['D4'],
                  NEE: ['H4'],
                  W  : ['E3', 'D3', 'C3', 'B3', 'A3'],
                  E  : ['G3', 'H3'],
                  SWW: ['D2'],
                  SEE: ['H2'],
                  SW : ['E2', 'D1'],
                  S  : ['F2', 'F1'],
                  SE : ['G2', 'H1'],
                  SSW: ['E1'],
                  SSE: ['G1'],
                ] as Map),

        G3(23, [7, 3],
                [ /* squares in directions from G3*/
                  NNW: ['F5'],
                  NNE: ['H5'],
                  NW : ['F4', 'E5', 'D6', 'C7', 'B8'],
                  N  : ['G4', 'G5', 'G6', 'G7', 'G8'],
                  NE : ['H4'],
                  NWW: ['E4'],
                  NEE: [],
                  W  : ['F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
                  E  : ['H3'],
                  SWW: ['E2'],
                  SEE: [],
                  SW : ['F2', 'E1'],
                  S  : ['G2', 'G1'],
                  SE : ['H2'],
                  SSW: ['F1'],
                  SSE: ['H1'],
                ] as Map),

        H3(24, [8, 3],
                [ /* squares in directions from H3*/
                  NNW: ['G5'],
                  NNE: [],
                  NW : ['G4', 'F5', 'E6', 'D7', 'C8'],
                  N  : ['H4', 'H5', 'H6', 'H7', 'H8'],
                  NE : [],
                  NWW: ['F4'],
                  NEE: [],
                  W  : ['G3', 'F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
                  E  : [],
                  SWW: ['F2'],
                  SEE: [],
                  SW : ['G2', 'F1'],
                  S  : ['H2', 'H1'],
                  SE : [],
                  SSW: ['G1'],
                  SSE: [],
                ] as Map),

        A4(25, [1, 4],
                [ /* squares in directions from A4*/
                  NNW: [],
                  NNE: ['B6'],
                  NW : [],
                  N  : ['A5', 'A6', 'A7', 'A8'],
                  NE : ['B5', 'C6', 'D7', 'E8'],
                  NWW: [],
                  NEE: ['C5'],
                  W  : [],
                  E  : ['B4', 'C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
                  SWW: [],
                  SEE: ['C3'],
                  SW : [],
                  S  : ['A3', 'A2', 'A1'],
                  SE : ['B3', 'C2', 'D1'],
                  SSW: [],
                  SSE: ['B2'],
                ] as Map),

        B4(26, [2, 4],
                [ /* squares in directions from B4*/
                  NNW: ['A6'],
                  NNE: ['C6'],
                  NW : ['A5'],
                  N  : ['B5', 'B6', 'B7', 'B8'],
                  NE : ['C5', 'D6', 'E7', 'F8'],
                  NWW: [],
                  NEE: ['D5'],
                  W  : ['A4'],
                  E  : ['C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
                  SWW: [],
                  SEE: ['D3'],
                  SW : ['A3'],
                  S  : ['B3', 'B2', 'B1'],
                  SE : ['C3', 'D2', 'E1'],
                  SSW: ['A2'],
                  SSE: ['C2'],
                ] as Map),

        C4(27, [3, 4],
                [ /* squares in directions from C4*/
                  NNW: ['B6'],
                  NNE: ['D6'],
                  NW : ['B5', 'A6'],
                  N  : ['C5', 'C6', 'C7', 'C8'],
                  NE : ['D5', 'E6', 'F7', 'G8'],
                  NWW: ['A5'],
                  NEE: ['E5'],
                  W  : ['B4', 'A4'],
                  E  : ['D4', 'E4', 'F4', 'G4', 'H4'],
                  SWW: ['A3'],
                  SEE: ['E3'],
                  SW : ['B3', 'A2'],
                  S  : ['C3', 'C2', 'C1'],
                  SE : ['D3', 'E2', 'F1'],
                  SSW: ['B2'],
                  SSE: ['D2'],
                ] as Map),

        D4(28, [4, 4],
                [ /* squares in directions from D4*/
                  NNW: ['C6'],
                  NNE: ['E6'],
                  NW : ['C5', 'B6', 'A7'],
                  N  : ['D5', 'D6', 'D7', 'D8'],
                  NE : ['E5', 'F6', 'G7', 'H8'],
                  NWW: ['B5'],
                  NEE: ['F5'],
                  W  : ['C4', 'B4', 'A4'],
                  E  : ['E4', 'F4', 'G4', 'H4'],
                  SWW: ['B3'],
                  SEE: ['F3'],
                  SW : ['C3', 'B2', 'A1'],
                  S  : ['D3', 'D2', 'D1'],
                  SE : ['E3', 'F2', 'G1'],
                  SSW: ['C2'],
                  SSE: ['E2'],
                ] as Map),

        E4(29, [5, 4],
                [ /* squares in directions from E4*/
                  NNW: ['D6'],
                  NNE: ['F6'],
                  NW : ['D5', 'C6', 'B7', 'A8'],
                  N  : ['E5', 'E6', 'E7', 'E8'],
                  NE : ['F5', 'G6', 'H7'],
                  NWW: ['C5'],
                  NEE: ['G5'],
                  W  : ['D4', 'C4', 'B4', 'A4'],
                  E  : ['F4', 'G4', 'H4'],
                  SWW: ['C3'],
                  SEE: ['G3'],
                  SW : ['D3', 'C2', 'B1'],
                  S  : ['E3', 'E2', 'E1'],
                  SE : ['F3', 'G2', 'H1'],
                  SSW: ['D2'],
                  SSE: ['F2'],
                ] as Map),

        F4(30, [6, 4],
                [ /* squares in directions from F4*/
                  NNW: ['E6'],
                  NNE: ['G6'],
                  NW : ['E5', 'D6', 'C7', 'B8'],
                  N  : ['F5', 'F6', 'F7', 'F8'],
                  NE : ['G5', 'H6'],
                  NWW: ['D5'],
                  NEE: ['H5'],
                  W  : ['E4', 'D4', 'C4', 'B4', 'A4'],
                  E  : ['G4', 'H4'],
                  SWW: ['D3'],
                  SEE: ['H3'],
                  SW : ['E3', 'D2', 'C1'],
                  S  : ['F3', 'F2', 'F1'],
                  SE : ['G3', 'H2'],
                  SSW: ['E2'],
                  SSE: ['G2'],
                ] as Map),

        G4(31, [7, 4],
                [ /* squares in directions from G4*/
                  NNW: ['F6'],
                  NNE: ['H6'],
                  NW : ['F5', 'E6', 'D7', 'C8'],
                  N  : ['G5', 'G6', 'G7', 'G8'],
                  NE : ['H5'],
                  NWW: ['E5'],
                  NEE: [],
                  W  : ['F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
                  E  : ['H4'],
                  SWW: ['E3'],
                  SEE: [],
                  SW : ['F3', 'E2', 'D1'],
                  S  : ['G3', 'G2', 'G1'],
                  SE : ['H3'],
                  SSW: ['F2'],
                  SSE: ['H2'],
                ] as Map),

        H4(32, [8, 4],
                [ /* squares in directions from H4*/
                  NNW: ['G6'],
                  NNE: [],
                  NW : ['G5', 'F6', 'E7', 'D8'],
                  N  : ['H5', 'H6', 'H7', 'H8'],
                  NE : [],
                  NWW: ['F5'],
                  NEE: [],
                  W  : ['G4', 'F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
                  E  : [],
                  SWW: ['F3'],
                  SEE: [],
                  SW : ['G3', 'F2', 'E1'],
                  S  : ['H3', 'H2', 'H1'],
                  SE : [],
                  SSW: ['G2'],
                  SSE: [],
                ] as Map),

        A5(33, [1, 5],
                [ /* squares in directions from A5*/
                  NNW: [],
                  NNE: ['B7'],
                  NW : [],
                  N  : ['A6', 'A7', 'A8'],
                  NE : ['B6', 'C7', 'D8'],
                  NWW: [],
                  NEE: ['C6'],
                  W  : [],
                  E  : ['B5', 'C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
                  SWW: [],
                  SEE: ['C4'],
                  SW : [],
                  S  : ['A4', 'A3', 'A2', 'A1'],
                  SE : ['B4', 'C3', 'D2', 'E1'],
                  SSW: [],
                  SSE: ['B3'],
                ] as Map),

        B5(34, [2, 5],
                [ /* squares in directions from B5*/
                  NNW: ['A7'],
                  NNE: ['C7'],
                  NW : ['A6'],
                  N  : ['B6', 'B7', 'B8'],
                  NE : ['C6', 'D7', 'E8'],
                  NWW: [],
                  NEE: ['D6'],
                  W  : ['A5'],
                  E  : ['C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
                  SWW: [],
                  SEE: ['D4'],
                  SW : ['A4'],
                  S  : ['B4', 'B3', 'B2', 'B1'],
                  SE : ['C4', 'D3', 'E2', 'F1'],
                  SSW: ['A3'],
                  SSE: ['C3'],
                ] as Map),

        C5(35, [3, 5],
                [ /* squares in directions from C5*/
                  NNW: ['B7'],
                  NNE: ['D7'],
                  NW : ['B6', 'A7'],
                  N  : ['C6', 'C7', 'C8'],
                  NE : ['D6', 'E7', 'F8'],
                  NWW: ['A6'],
                  NEE: ['E6'],
                  W  : ['B5', 'A5'],
                  E  : ['D5', 'E5', 'F5', 'G5', 'H5'],
                  SWW: ['A4'],
                  SEE: ['E4'],
                  SW : ['B4', 'A3'],
                  S  : ['C4', 'C3', 'C2', 'C1'],
                  SE : ['D4', 'E3', 'F2', 'G1'],
                  SSW: ['B3'],
                  SSE: ['D3'],
                ] as Map),

        D5(36, [4, 5],
                [ /* squares in directions from D5*/
                  NNW: ['C7'],
                  NNE: ['E7'],
                  NW : ['C6', 'B7', 'A8'],
                  N  : ['D6', 'D7', 'D8'],
                  NE : ['E6', 'F7', 'G8'],
                  NWW: ['B6'],
                  NEE: ['F6'],
                  W  : ['C5', 'B5', 'A5'],
                  E  : ['E5', 'F5', 'G5', 'H5'],
                  SWW: ['B4'],
                  SEE: ['F4'],
                  SW : ['C4', 'B3', 'A2'],
                  S  : ['D4', 'D3', 'D2', 'D1'],
                  SE : ['E4', 'F3', 'G2', 'H1'],
                  SSW: ['C3'],
                  SSE: ['E3'],
                ] as Map),

        E5(37, [5, 5],
                [ /* squares in directions from E5*/
                  NNW: ['D7'],
                  NNE: ['F7'],
                  NW : ['D6', 'C7', 'B8'],
                  N  : ['E6', 'E7', 'E8'],
                  NE : ['F6', 'G7', 'H8'],
                  NWW: ['C6'],
                  NEE: ['G6'],
                  W  : ['D5', 'C5', 'B5', 'A5'],
                  E  : ['F5', 'G5', 'H5'],
                  SWW: ['C4'],
                  SEE: ['G4'],
                  SW : ['D4', 'C3', 'B2', 'A1'],
                  S  : ['E4', 'E3', 'E2', 'E1'],
                  SE : ['F4', 'G3', 'H2'],
                  SSW: ['D3'],
                  SSE: ['F3'],
                ] as Map),

        F5(38, [6, 5],
                [ /* squares in directions from F5*/
                  NNW: ['E7'],
                  NNE: ['G7'],
                  NW : ['E6', 'D7', 'C8'],
                  N  : ['F6', 'F7', 'F8'],
                  NE : ['G6', 'H7'],
                  NWW: ['D6'],
                  NEE: ['H6'],
                  W  : ['E5', 'D5', 'C5', 'B5', 'A5'],
                  E  : ['G5', 'H5'],
                  SWW: ['D4'],
                  SEE: ['H4'],
                  SW : ['E4', 'D3', 'C2', 'B1'],
                  S  : ['F4', 'F3', 'F2', 'F1'],
                  SE : ['G4', 'H3'],
                  SSW: ['E3'],
                  SSE: ['G3'],
                ] as Map),

        G5(39, [7, 5],
                [ /* squares in directions from G5*/
                  NNW: ['F7'],
                  NNE: ['H7'],
                  NW : ['F6', 'E7', 'D8'],
                  N  : ['G6', 'G7', 'G8'],
                  NE : ['H6'],
                  NWW: ['E6'],
                  NEE: [],
                  W  : ['F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
                  E  : ['H5'],
                  SWW: ['E4'],
                  SEE: [],
                  SW : ['F4', 'E3', 'D2', 'C1'],
                  S  : ['G4', 'G3', 'G2', 'G1'],
                  SE : ['H4'],
                  SSW: ['F3'],
                  SSE: ['H3'],
                ] as Map),

        H5(40, [8, 5],
                [ /* squares in directions from H5*/
                  NNW: ['G7'],
                  NNE: [],
                  NW : ['G6', 'F7', 'E8'],
                  N  : ['H6', 'H7', 'H8'],
                  NE : [],
                  NWW: ['F6'],
                  NEE: [],
                  W  : ['G5', 'F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
                  E  : [],
                  SWW: ['F4'],
                  SEE: [],
                  SW : ['G4', 'F3', 'E2', 'D1'],
                  S  : ['H4', 'H3', 'H2', 'H1'],
                  SE : [],
                  SSW: ['G3'],
                  SSE: [],
                ] as Map),

        A6(41, [1, 6],
                [ /* squares in directions from A6*/
                  NNW: [],
                  NNE: ['B8'],
                  NW : [],
                  N  : ['A7', 'A8'],
                  NE : ['B7', 'C8'],
                  NWW: [],
                  NEE: ['C7'],
                  W  : [],
                  E  : ['B6', 'C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
                  SWW: [],
                  SEE: ['C5'],
                  SW : [],
                  S  : ['A5', 'A4', 'A3', 'A2', 'A1'],
                  SE : ['B5', 'C4', 'D3', 'E2', 'F1'],
                  SSW: [],
                  SSE: ['B4'],
                ] as Map),

        B6(42, [2, 6],
                [ /* squares in directions from B6*/
                  NNW: ['A8'],
                  NNE: ['C8'],
                  NW : ['A7'],
                  N  : ['B7', 'B8'],
                  NE : ['C7', 'D8'],
                  NWW: [],
                  NEE: ['D7'],
                  W  : ['A6'],
                  E  : ['C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
                  SWW: [],
                  SEE: ['D5'],
                  SW : ['A5'],
                  S  : ['B5', 'B4', 'B3', 'B2', 'B1'],
                  SE : ['C5', 'D4', 'E3', 'F2', 'G1'],
                  SSW: ['A4'],
                  SSE: ['C4'],
                ] as Map),

        C6(43, [3, 6],
                [ /* squares in directions from C6*/
                  NNW: ['B8'],
                  NNE: ['D8'],
                  NW : ['B7', 'A8'],
                  N  : ['C7', 'C8'],
                  NE : ['D7', 'E8'],
                  NWW: ['A7'],
                  NEE: ['E7'],
                  W  : ['B6', 'A6'],
                  E  : ['D6', 'E6', 'F6', 'G6', 'H6'],
                  SWW: ['A5'],
                  SEE: ['E5'],
                  SW : ['B5', 'A4'],
                  S  : ['C5', 'C4', 'C3', 'C2', 'C1'],
                  SE : ['D5', 'E4', 'F3', 'G2', 'H1'],
                  SSW: ['B4'],
                  SSE: ['D4'],
                ] as Map),

        D6(44, [4, 6],
                [ /* squares in directions from D6*/
                  NNW: ['C8'],
                  NNE: ['E8'],
                  NW : ['C7', 'B8'],
                  N  : ['D7', 'D8'],
                  NE : ['E7', 'F8'],
                  NWW: ['B7'],
                  NEE: ['F7'],
                  W  : ['C6', 'B6', 'A6'],
                  E  : ['E6', 'F6', 'G6', 'H6'],
                  SWW: ['B5'],
                  SEE: ['F5'],
                  SW : ['C5', 'B4', 'A3'],
                  S  : ['D5', 'D4', 'D3', 'D2', 'D1'],
                  SE : ['E5', 'F4', 'G3', 'H2'],
                  SSW: ['C4'],
                  SSE: ['E4'],
                ] as Map),

        E6(45, [5, 6],
                [ /* squares in directions from E6*/
                  NNW: ['D8'],
                  NNE: ['F8'],
                  NW : ['D7', 'C8'],
                  N  : ['E7', 'E8'],
                  NE : ['F7', 'G8'],
                  NWW: ['C7'],
                  NEE: ['G7'],
                  W  : ['D6', 'C6', 'B6', 'A6'],
                  E  : ['F6', 'G6', 'H6'],
                  SWW: ['C5'],
                  SEE: ['G5'],
                  SW : ['D5', 'C4', 'B3', 'A2'],
                  S  : ['E5', 'E4', 'E3', 'E2', 'E1'],
                  SE : ['F5', 'G4', 'H3'],
                  SSW: ['D4'],
                  SSE: ['F4'],
                ] as Map),

        F6(46, [6, 6],
                [ /* squares in directions from F6*/
                  NNW: ['E8'],
                  NNE: ['G8'],
                  NW : ['E7', 'D8'],
                  N  : ['F7', 'F8'],
                  NE : ['G7', 'H8'],
                  NWW: ['D7'],
                  NEE: ['H7'],
                  W  : ['E6', 'D6', 'C6', 'B6', 'A6'],
                  E  : ['G6', 'H6'],
                  SWW: ['D5'],
                  SEE: ['H5'],
                  SW : ['E5', 'D4', 'C3', 'B2', 'A1'],
                  S  : ['F5', 'F4', 'F3', 'F2', 'F1'],
                  SE : ['G5', 'H4'],
                  SSW: ['E4'],
                  SSE: ['G4'],
                ] as Map),

        G6(47, [7, 6],
                [ /* squares in directions from G6*/
                  NNW: ['F8'],
                  NNE: ['H8'],
                  NW : ['F7', 'E8'],
                  N  : ['G7', 'G8'],
                  NE : ['H7'],
                  NWW: ['E7'],
                  NEE: [],
                  W  : ['F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
                  E  : ['H6'],
                  SWW: ['E5'],
                  SEE: [],
                  SW : ['F5', 'E4', 'D3', 'C2', 'B1'],
                  S  : ['G5', 'G4', 'G3', 'G2', 'G1'],
                  SE : ['H5'],
                  SSW: ['F4'],
                  SSE: ['H4'],
                ] as Map),

        H6(48, [8, 6],
                [ /* squares in directions from H6*/
                  NNW: ['G8'],
                  NNE: [],
                  NW : ['G7', 'F8'],
                  N  : ['H7', 'H8'],
                  NE : [],
                  NWW: ['F7'],
                  NEE: [],
                  W  : ['G6', 'F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
                  E  : [],
                  SWW: ['F5'],
                  SEE: [],
                  SW : ['G5', 'F4', 'E3', 'D2', 'C1'],
                  S  : ['H5', 'H4', 'H3', 'H2', 'H1'],
                  SE : [],
                  SSW: ['G4'],
                  SSE: [],
                ] as Map),

        A7(49, [1, 7],
                [ /* squares in directions from A7*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : ['A8'],
                  NE : ['B8'],
                  NWW: [],
                  NEE: ['C8'],
                  W  : [],
                  E  : ['B7', 'C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
                  SWW: [],
                  SEE: ['C6'],
                  SW : [],
                  S  : ['A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
                  SE : ['B6', 'C5', 'D4', 'E3', 'F2', 'G1'],
                  SSW: [],
                  SSE: ['B5'],
                ] as Map),

        B7(50, [2, 7],
                [ /* squares in directions from B7*/
                  NNW: [],
                  NNE: [],
                  NW : ['A8'],
                  N  : ['B8'],
                  NE : ['C8'],
                  NWW: [],
                  NEE: ['D8'],
                  W  : ['A7'],
                  E  : ['C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
                  SWW: [],
                  SEE: ['D6'],
                  SW : ['A6'],
                  S  : ['B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
                  SE : ['C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
                  SSW: ['A5'],
                  SSE: ['C5'],
                ] as Map),

        C7(51, [3, 7],
                [ /* squares in directions from C7*/
                  NNW: [],
                  NNE: [],
                  NW : ['B8'],
                  N  : ['C8'],
                  NE : ['D8'],
                  NWW: ['A8'],
                  NEE: ['E8'],
                  W  : ['B7', 'A7'],
                  E  : ['D7', 'E7', 'F7', 'G7', 'H7'],
                  SWW: ['A6'],
                  SEE: ['E6'],
                  SW : ['B6', 'A5'],
                  S  : ['C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
                  SE : ['D6', 'E5', 'F4', 'G3', 'H2'],
                  SSW: ['B5'],
                  SSE: ['D5'],
                ] as Map),

        D7(52, [4, 7],
                [ /* squares in directions from D7*/
                  NNW: [],
                  NNE: [],
                  NW : ['C8'],
                  N  : ['D8'],
                  NE : ['E8'],
                  NWW: ['B8'],
                  NEE: ['F8'],
                  W  : ['C7', 'B7', 'A7'],
                  E  : ['E7', 'F7', 'G7', 'H7'],
                  SWW: ['B6'],
                  SEE: ['F6'],
                  SW : ['C6', 'B5', 'A4'],
                  S  : ['D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
                  SE : ['E6', 'F5', 'G4', 'H3'],
                  SSW: ['C5'],
                  SSE: ['E5'],
                ] as Map),

        E7(53, [5, 7],
                [ /* squares in directions from E7*/
                  NNW: [],
                  NNE: [],
                  NW : ['D8'],
                  N  : ['E8'],
                  NE : ['F8'],
                  NWW: ['C8'],
                  NEE: ['G8'],
                  W  : ['D7', 'C7', 'B7', 'A7'],
                  E  : ['F7', 'G7', 'H7'],
                  SWW: ['C6'],
                  SEE: ['G6'],
                  SW : ['D6', 'C5', 'B4', 'A3'],
                  S  : ['E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
                  SE : ['F6', 'G5', 'H4'],
                  SSW: ['D5'],
                  SSE: ['F5'],
                ] as Map),

        F7(54, [6, 7],
                [ /* squares in directions from F7*/
                  NNW: [],
                  NNE: [],
                  NW : ['E8'],
                  N  : ['F8'],
                  NE : ['G8'],
                  NWW: ['D8'],
                  NEE: ['H8'],
                  W  : ['E7', 'D7', 'C7', 'B7', 'A7'],
                  E  : ['G7', 'H7'],
                  SWW: ['D6'],
                  SEE: ['H6'],
                  SW : ['E6', 'D5', 'C4', 'B3', 'A2'],
                  S  : ['F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
                  SE : ['G6', 'H5'],
                  SSW: ['E5'],
                  SSE: ['G5'],
                ] as Map),

        G7(55, [7, 7],
                [ /* squares in directions from G7*/
                  NNW: [],
                  NNE: [],
                  NW : ['F8'],
                  N  : ['G8'],
                  NE : ['H8'],
                  NWW: ['E8'],
                  NEE: [],
                  W  : ['F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
                  E  : ['H7'],
                  SWW: ['E6'],
                  SEE: [],
                  SW : ['F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
                  S  : ['G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
                  SE : ['H6'],
                  SSW: ['F5'],
                  SSE: ['H5'],
                ] as Map),

        H7(56, [8, 7],
                [ /* squares in directions from H7*/
                  NNW: [],
                  NNE: [],
                  NW : ['G8'],
                  N  : ['H8'],
                  NE : [],
                  NWW: ['F8'],
                  NEE: [],
                  W  : ['G7', 'F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
                  E  : [],
                  SWW: ['F6'],
                  SEE: [],
                  SW : ['G6', 'F5', 'E4', 'D3', 'C2', 'B1'],
                  S  : ['H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
                  SE : [],
                  SSW: ['G5'],
                  SSE: [],
                ] as Map),

        A8(57, [1, 8],
                [ /* squares in directions from A8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : [],
                  E  : ['B8', 'C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
                  SWW: [],
                  SEE: ['C7'],
                  SW : [],
                  S  : ['A7', 'A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
                  SE : ['B7', 'C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
                  SSW: [],
                  SSE: ['B6'],
                ] as Map),

        B8(58, [2, 8],
                [ /* squares in directions from B8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['A8'],
                  E  : ['C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
                  SWW: [],
                  SEE: ['D7'],
                  SW : ['A7'],
                  S  : ['B7', 'B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
                  SE : ['C7', 'D6', 'E5', 'F4', 'G3', 'H2'],
                  SSW: ['A6'],
                  SSE: ['C6'],
                ] as Map),

        C8(59, [3, 8],
                [ /* squares in directions from C8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['B8', 'A8'],
                  E  : ['D8', 'E8', 'F8', 'G8', 'H8'],
                  SWW: ['A7'],
                  SEE: ['E7'],
                  SW : ['B7', 'A6'],
                  S  : ['C7', 'C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
                  SE : ['D7', 'E6', 'F5', 'G4', 'H3'],
                  SSW: ['B6'],
                  SSE: ['D6'],
                ] as Map),

        D8(60, [4, 8],
                [ /* squares in directions from D8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['C8', 'B8', 'A8'],
                  E  : ['E8', 'F8', 'G8', 'H8'],
                  SWW: ['B7'],
                  SEE: ['F7'],
                  SW : ['C7', 'B6', 'A5'],
                  S  : ['D7', 'D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
                  SE : ['E7', 'F6', 'G5', 'H4'],
                  SSW: ['C6'],
                  SSE: ['E6'],
                ] as Map),

        E8(61, [5, 8],
                [ /* squares in directions from E8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['D8', 'C8', 'B8', 'A8'],
                  E  : ['F8', 'G8', 'H8'],
                  SWW: ['C7'],
                  SEE: ['G7'],
                  SW : ['D7', 'C6', 'B5', 'A4'],
                  S  : ['E7', 'E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
                  SE : ['F7', 'G6', 'H5'],
                  SSW: ['D6'],
                  SSE: ['F6'],
                ] as Map),

        F8(62, [6, 8],
                [ /* squares in directions from F8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['E8', 'D8', 'C8', 'B8', 'A8'],
                  E  : ['G8', 'H8'],
                  SWW: ['D7'],
                  SEE: ['H7'],
                  SW : ['E7', 'D6', 'C5', 'B4', 'A3'],
                  S  : ['F7', 'F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
                  SE : ['G7', 'H6'],
                  SSW: ['E6'],
                  SSE: ['G6'],
                ] as Map),

        G8(63, [7, 8],
                [ /* squares in directions from G8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
                  E  : ['H8'],
                  SWW: ['E7'],
                  SEE: [],
                  SW : ['F7', 'E6', 'D5', 'C4', 'B3', 'A2'],
                  S  : ['G7', 'G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
                  SE : ['H7'],
                  SSW: ['F6'],
                  SSE: ['H6'],
                ] as Map),

        H8(64, [8, 8],
                [ /* squares in directions from H8*/
                  NNW: [],
                  NNE: [],
                  NW : [],
                  N  : [],
                  NE : [],
                  NWW: [],
                  NEE: [],
                  W  : ['G8', 'F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
                  E  : [],
                  SWW: ['F7'],
                  SEE: [],
                  SW : ['G7', 'F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
                  S  : ['H7', 'H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
                  SE : [],
                  SSW: ['G6'],
                  SSE: [],
                ] as Map),


        public int n
        public int x
        public int y
        private Map<Direction, String[]> map

        private List<String> squaresInDirection(Direction direction) {
                def key = direction.toString()
                log.debug "$key ${map.get(key)}"
                map.get(key)
        }

        // PATH TO
        def path(Direction direction, int step, boolean withLast = false) {
                def path = squaresInDirection(direction)
                def lastElementIndex = step - (withLast ? 1 : 2)
                if (path == null || lastElementIndex < 0) {
                        return []
                } else {
                        return path[0..lastElementIndex] ?: []
                }
        }

        def Square to(Direction direction, int step) {
                Square.valueOf(squaresInDirection(direction)[step - 1])
        }

        private Square(int n, ArrayList<Integer> xy, Map<Direction, String[]> map) {
                this.n = n
                this.x = xy[0]
                this.y = xy[1]
                this.map = map
        }

        public static byXY(int x, int y) {
                Square.values().find { it.x == x && it.y == y }
        }

        @Override
        String toString() {
                name()
        }
}
